Repository goOHDARS/backend, pull requests merged in 2024-05, with the labels that each got.

#6 Add Workflows for Lint and Deploy
  .github/workflows/firebase-deploy.yml
  .github/workflows/firebase-lint.yml
  README.md
  functions/.gitignore
  functions/package-lock.json
  functions/package.json
Labels: feature, backend

#7 Never allow semicolons
  functions/.eslintrc.js
Labels: chore

#11 added helper functions
  functions/src/controllers/MajorsController.ts
  functions/src/controllers/UserController.ts
Labels: good first issue, chore, backend

#9 Add Makefile, ran npm install --save firebse-functions@latest
  Makefile
  functions/package-lock.json
  functions/package.json
Labels: feature, chore, backend

#12 Add types and helper functions
  functions/.eslintrc.js
  functions/src/controllers/CoursesController.ts
  functions/src/controllers/MajorsController.ts
  functions/src/controllers/UserController.ts
  functions/src/index.ts
  functions/src/middleware/validation.ts
  functions/src/utils.ts
Labels: feature, backend

#13 Onboarding Endpoints
  functions/src/controllers/CoursesController.ts
  functions/src/controllers/MajorsController.ts
  functions/src/controllers/UserController.ts
  functions/src/index.ts
  functions/src/utils.ts
Labels: feature, backend

#14 Feature/add random pokemon
  functions/package.json
  functions/src/controllers/UserController.ts
Labels: feature
